### ISSUE TITLE
Cannot start anymore

### ISSUE THREAD

**Issue by thekane6** [pixelstuermer/pixieset-downloader#9]
Following Error

> D:\pixieset-downloader-1.0.1>python pixieset-downloader.py https://josevilla.pixieset.com/client/loadphotos 3301757 lilyandjonathan highlights k************************e -r ".*xxlarge.*" -f "example" -s 
> 
> Traceback (most recent call last):
>   File "D:\pixieset-downloader-1.0.1\pixieset-downloader.py", line 113, in <module>
>     main()
>   File "D:\pixieset-downloader-1.0.1\pixieset-downloader.py", line 88, in main
>     page_data = json.loads(page_data_response.json()['content'])
>   File "C:\Users\user\AppData\Roaming\Python\Python39\site-packages\requests\models.py", line 910, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "C:\Program Files\Python39\lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "C:\Program Files\Python39\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Program Files\Python39\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

all requirements installed without a problem.
a few months back it was running without any issue

**Comment by pixelstuermer** [comment]
> all requirements installed without a problem. a few months back it was running without any issue

@thekane6 did you get new/valid access credentials before executing the script?

**Comment by thekane6** [comment]
> > all requirements installed without a problem. a few months back it was running without any issue
> 
> @thekane6 did you get new/valid access credentials before executing the script?

yes, did a refresh of the page and copied the keys. tried it also with the mentioned example

**Comment by pixelstuermer** [comment]
> > > all requirements installed without a problem. a few months back it was running without any issue
> > 
> > 
> > @thekane6 did you get new/valid access credentials before executing the script?
> 
> yes, did a refresh of the page and copied the keys. tried it also with the mentioned example

Found it. Give me a minute 😄

**Comment by pixelstuermer** [comment]
@thekane6 please use version [1.0.2](https://github.com/pixelstuermer/pixieset-downloader/tree/1.0.2) 👍🏻

**Comment by thekane6** [comment]
> @thekane6 please use version [1.0.2](https://github.com/pixelstuermer/pixieset-downloader/tree/1.0.2) 👍🏻

thank you, it works again!
Great tool!

**Comment by pixelstuermer** [comment]
> > @thekane6 please use version [1.0.2](https://github.com/pixelstuermer/pixieset-downloader/tree/1.0.2) 👍🏻
> 
> thank you, it works again! Great tool!

You're welcome!
